basic:
    name: Isel
    environments:
        production: 'https://www.isel.pt'
        staging: 'https://site.isel.pt/'
        development: ''
    breakpoints:
        - 560
        - 768
        - 1200
    pages:
        - /
        - /en
        - /user/register
        - /o-isel-apresenta-se/estudar-no-isel
        - /o-isel-apresenta-se/onde-estamos
        - /isel-nos-media
        - /o-isel-apresenta-se/os-nossos-espacos
        - /plano-para-igualdade-de-genero
        - /servicos/servico-de-comunicacao-e-imagem/identidade-institucional
        - /a-descoberta-do-isel/open-days
        - /a-descoberta-do-isel/isel-alive
        - /a-descoberta-do-isel/energy-week
        - /o-isel-apresenta-se/sustentabilidade/ambiente/isel-eco-campus
        - /o-isel-apresenta-se/sustentabilidade/ambiente/isel-eco-campus/isel-carbono-zero
        - /projetos-com-alunos
        - /isel/quem-somos/instituicao
        - /isel/quem-somos/orgaos
        - /isel/quem-somos/departamentos
        - /isel/quem-somos/servicos
        - /quem-somos/documentos-publicos
        - /quem-somos/qualidade
        - /o-isel-apresenta-se/sustentabilidade
        - /candidatos/porque_o_isel
        - /ensino/candidatos/modalidades-de-ingresso
        - /servicos/modalidades-de-ingresso/estudante-internacional
        - /cursos/licenciaturas
        - /cursos/mestrados
        - /cursos/pos-graduacoes
        - /cursos/outros-cursos
        - /ensino/programas-de-mobilidade/erasmus-alunos-outgoing/informacoes-gerais
        - /ensino/programas-de-mobilidade/erasmus-alunos-incoming/informacoes-gerais
        - /ensino/programas-de-mobilidade/erasmus-staff/informacoes-gerais
        - /ensino/programas-de-mobilidade/bip
        - /ensino/programas-de-mobilidade/outros-programas/informacoes-gerais/programas-de-intercambio
        - /comunidade/estudantes/informacoes-academicas
        - /comunidade/estudantes/informacoes-para-novos-alunos
        - /servicos/comunidade/estudantes/espaco-de-apoio-ao-aluno
        - /comunidade/estudantes/bolsa-para-estudantes
        - /comunidade/estudantes/premios-para-estudantes
        - /servicos/biblioteca
        - /servicos/comunidade/estudantes/empregabilidade/alunos/plataforma-de-emprego
        - /comunidade/alem-aulas/associacao-de-estudantes
        - /comunidade/alem-aulas/estudantina-academica
        - /comunidade/alem-aulas/tuna-feminina
        - /a-descoberta-do-isel/isel-formula-student
        - /servicos/comunidade/estudantes/integracao
        - /comunidade/alem-aulas/world-action-isel
        - /clube-da-matematica
        - /comunidade/alumni/rede-alumnisel
        - /comunidade/alumni/rede-alumnisel/iniciativas
        - /comunidade/alumni/rede-alumnisel/fundadores
        - /ecossistema-de-inovacao/unidades-de-ied/estruturas-e-unidades
        - /investigacao-e-inovacao/ecossistema-de-inovacao/projetos
        - /investigacao-e-inovacao/ecossistema-e-inovacao/publicacoes
        - /investigacao-e-inovacao/ecossistema-e-inovacao/propriedade-intelectual
        - /investigacao-e-inovacao/ecossistema-de-inovacao/procedimento-de-aquisicao-id
        - /investigacao-e-incovacao/empreendedorismo/incubadora-de-empresas/modelos-de-incubacao
        - /servicos/investigacao-e-inovacao/empreendedorismo/innovation-labs
        - /servicos/investiga%C3%A7%C3%A3o-e-inova%C3%A7%C3%A3o/oportunidades/financiamento
        - /servicos/investigacao-e-inovacao/oportunidades/bolsas-de-investigacao
        - /isel-guest-editors-special-issues
        - /noticias/isel-lanca-os-primeiros-moocs-no-ambito-do-projeto-prodigi
        - /eventos/forum-de-engenharia-quimica-e-biologica-e-biomedica-ifeqb2-2025
        - /eventos/math25-networking-workshop
        - /eventos/21a-international-conference-european-energy-markets
        - /noticias/exposicao-anuario-lusa-2024-inaugurada-no-isel-com-mesa-redonda-sobre-jornalismo-e-imagem
        - /noticias/visita-tecnica-navigator-company-aproxima-estudantes-do-isel-da-realidade-industrial
        - /noticias/isel-acolheu-encontro-de-jovens-ser-cool-ser-inclusao
        - /noticias/ipl-em-missao-ao-brasil-pela-1o-vez-com-o-ccisp
        - /noticias/primeiro-open-day-de-2025-reune-mais-de-uma-centena-de-participantes
        - /noticias/isel-na-futuralia-2025
        - /noticias/isel-marca-presenca-na-tektonica-2025
        - /news
        - /eventos/seminario-gestao-de-incerteza-num-contexto-de-planeamento-de-capacidade
        - /eventos/ride-bike-ipl
        - /eventos/clean-beach-ipl
        - /eventos/grupos-de-intervencao-na-ansiedade
        - /eventos/jornada-tecnica-solucoes-de-engenharia-digital-e-automacao-industrial
        - /eventos/irs-jovem-2025-nova-data
        - /eventos/openlabs-clube-bioinformatica
        - /eventos/seminario-de-fisica-sensores-distribuidos-de-fundo-marinho
        - /eventos/open-days-2025
        - /eventos/seminario-unire-beyond-bond
        - /eventos
        - /premios-e-eventos-externos
        - /horarios-de-salas-de-estudo
        - /servicos/servico-de-gestao-de-recursos-humanos/concursos-de-pessoal
        - /informacoes
        - /sugestoes-reclamacoes-ou-denuncias
        - /servicos/servico-de-informatica-e-redes-de-comunicacao/recursos-informaticos
        - /informacoes-academicas/calendario-academico
        - /termos-e-condicoes
        - /politica-de-privacidade
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 20
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: "(function () {\n  const banner = document.querySelector(\".eu-cookie-compliance-banner\");\n  if (banner) {\n    banner.style.display = \"none\";\n  }\n})();\n"
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
